### PR TITLE
Login Backend Features

### PR DESCRIPTION
**Pull request by justinyh**
- Added DB communication; now checks DB for both google user and for traditional login
- Added JSON Web Token that is stored in client's browser that we can use to ensure user is authenticated when accessing the API
- Added route for traditional login, hashed password using pbkdf2 & SHA-512
- Added error checking, returns 401 Status + json error message in the format { message: "error message here" }

Front end currently not working for traditional login, but you can use postman. Add a Basic authorization header.
Test username: justinyh@usc.edu
Test password: password

### CODE REVIEW

**Comment by justinyh** [comment]
Lol accidentally exposed our database uri to the world. I added you all to the MongoDB Atlas instance I'm using. There, if you click "connect", you can find the uri that you can paste in on app.js. Can y'all look over these changes and approve/merge them in? Feel free to clean it up & extract functions out with repeated code.

**Comment by justinyh** [comment]
[Login (both Google & Traditional) - Back end](https://trello.com/c/AzmNcjfZ/29-login-both-google-traditional-back-end)

**Review by Drakran — COMMENTED** [review]
I took a quick look looks like a good starting point for the mongo stuff for us to build off. We probably should move the route from app.js to like a mongoRoute.js just so app.js isnt crowded. Also i see fetch I now fetch.

**Review by hnguyen0 — APPROVED** [review]

**Comment by Drakran** [comment]
I revise my previous comment looking more closely you did it Justin I thought it was something else not enough backend chops for me.

**Pull request merged**
